### ISSUE TITLE
[Bug] 'Unexpected token ?' when trying to use 'npx create-fullstack-app <dir_name>'

### ISSUE THREAD

**Issue by Ezopek** [Divlo/create-fullstack-app#44]
So, I just tried to generate project using `npx create-fullstack-app test`
I tried with already created `test` dir, and without it. Also tried with `sudo` but got nothing.

```
ezop@ezop-linux:~/work$ ls -al
total 16
drwxrwxr-x  4 ezop ezop 4096 kwi 15 22:10 .
drwxr-xr-x 23 ezop ezop 4096 kwi 15 22:10 ..
drwxrwxr-x  7 ezop ezop 4096 kwi 15 21:53 clients-reminder
drwxrwxr-x  2 ezop ezop 4096 kwi 15 22:10 test
ezop@ezop-linux:~/work$ npx create-fullstack-app test
npx: installed 152 in 5.214s
Unexpected token ?
```

Im on Ubuntu 20.04.2 LTS
```
ezop@ezop-linux:~/work$ npm --version
6.14.4
```

## Steps To Reproduce

1. Just use `npx create-fullstack-app test`

## The current behavior
```
ezop@ezop-linux:~/work$ npx create-fullstack-app test
npx: installed 152 in 5.214s
Unexpected token ?
```

## The expected behavior
Possibly: "It will ask you some questions (template(s), name, description, etc.), when answered, it will copy and install all the dependencies needed for your project."

**Comment by Divlo** [comment]
Thanks for your report! @Ezopek 
I can't reproduce the issue, I'm also on Ubuntu 20.04 LTS. Could you tell me, what version of `npm` and `node` do you have ?
```sh
node --version
npm --version
```

**Comment by Divlo** [comment]
Please reopen if you have any others concern.
