### ISSUE TITLE
Mongodb & Fastify

### ISSUE THREAD

**Issue by Aslemammad** [Divlo/create-fullstack-app#6]
I loved this package. I'll be happy If You'd add MongoDB and Fastify support.

**Comment by Divlo** [comment]
Hey, 

Sure, do you think you could do a pull-request ?
I should write a CONTRIBUTING.md file and ISSUE_TEMPLATE.md.

Basically you can create a new template by following these steps : 
- Create a new folder  `/templates/ap/<template-name>`, where `<template-name>` you could name it something like `fastify-mongodb` and put the template files in there.
- Then in the `/src/constants/templateChoices.ts` file, you can edit the templateChoices variable, so you can add a new object in the array of the `api` key, with `name` property and the path of the template folder created in step one.
For example it could be something like this :
```ts
{
  name: 'Fastify with MongoDB',
  value: {
    path: path.join(TEMPLATE_API_PATH, 'fastify-mongodb')
  }
}
```

Feel free to discuss there, if there is something you don't understand or questions. 😃
I could work on that, but I never used Fastify. Anyway thank you for your interest and feedback, looking forward to discuss there.

**Comment by Aslemammad** [comment]
Hello, after publishing the Contributing.md, I'll take this PR and I'll add this feature. Thanks.

**Comment by Aslemammad** [comment]
I'm adding the js template, because this project I think it should be wider. I'll add the ts version early.

**Comment by Aslemammad** [comment]
https://github.com/Divlo/create-fullstack-app/pull/7
